// <auto-generated />
using System;
using Admission.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Admission.Api.Migrations
{
    [DbContext(typeof(AdmissionDbContext))]
    partial class AdmissionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Admission.Api.Models.Applicant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicantAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("applicant_address");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("birth_date");

                    b.Property<string>("Citizenship")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("citizenship");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("ForeignLanguage")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("foreign_language");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("gender");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("ParentsAddress")
                        .HasColumnType("text")
                        .HasColumnName("parents_address");

                    b.Property<string>("PassportData")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("passport_data");

                    b.Property<string>("Patronymic")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("patronymic");

                    b.HasKey("Id");

                    b.HasIndex("PassportData")
                        .IsUnique();

                    b.ToTable("applicants", (string)null);
                });

            modelBuilder.Entity("Admission.Api.Models.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Applicantid")
                        .HasColumnType("integer");

                    b.Property<decimal?>("AverageScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("average_score");

                    b.Property<string>("DocumentNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("document_number");

                    b.Property<string>("DocumentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("document_type");

                    b.Property<string>("EducationalInstitution")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("educational_institution");

                    b.Property<decimal?>("EgeScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("ege_score");

                    b.Property<string>("Faculty")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("faculty");

                    b.Property<int?>("GraduationYear")
                        .HasColumnType("integer")
                        .HasColumnName("graduation_year");

                    b.Property<string>("GroupNumber")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("group_number");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("specialty");

                    b.HasKey("Id");

                    b.HasIndex("Applicantid");

                    b.ToTable("applications", (string)null);
                });

            modelBuilder.Entity("Admission.Api.Models.ExamResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Applicationid")
                        .HasColumnType("integer");

                    b.Property<string>("Classroom")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("classroom");

                    b.Property<DateTime>("ExamDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("exam_date");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("subject");

                    b.HasKey("Id");

                    b.HasIndex("Applicationid", "Subject")
                        .IsUnique();

                    b.ToTable("exam_results", (string)null);
                });

            modelBuilder.Entity("Admission.Api.Models.SubjectGrade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Applicationid")
                        .HasColumnType("integer");

                    b.Property<int>("Grade")
                        .HasColumnType("integer")
                        .HasColumnName("grade");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("subject");

                    b.HasKey("Id");

                    b.HasIndex("Applicationid", "Subject")
                        .IsUnique();

                    b.ToTable("subject_grades", (string)null);
                });

            modelBuilder.Entity("Admission.Api.Models.Application", b =>
                {
                    b.HasOne("Admission.Api.Models.Applicant", "Applicant")
                        .WithMany("Applications")
                        .HasForeignKey("Applicantid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Applicant");
                });

            modelBuilder.Entity("Admission.Api.Models.ExamResult", b =>
                {
                    b.HasOne("Admission.Api.Models.Application", "Application")
                        .WithMany("ExamResults")
                        .HasForeignKey("Applicationid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("Admission.Api.Models.SubjectGrade", b =>
                {
                    b.HasOne("Admission.Api.Models.Application", "Application")
                        .WithMany("SubjectGrades")
                        .HasForeignKey("Applicationid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("Admission.Api.Models.Applicant", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("Admission.Api.Models.Application", b =>
                {
                    b.Navigation("ExamResults");

                    b.Navigation("SubjectGrades");
                });
#pragma warning restore 612, 618
        }
    }
}
